/* generated by pull.js */
const manifest = {
  "name": "快捷导出素材",
  "description": "在造型 / 背景 / 声音列表里右键任意素材，菜单中会多出一项“导出全部素材”，一点即可把当前目标这一类素材（全部造型、全部背景或全部声音）打包成 zip 下载。",
  "credits": [
    {
      "name": "Bilup"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "recommended"
  ],
  "editorOnly": true,
  "enabledByDefault": true,
  "dynamicDisable": true
};
export default manifest;
